services:
  - type: web
    name: mohannad-services
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Mohannad_Project_V2.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --browser.gatherUsageStats=false
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
